version: '3'
services:
  volttron:
    container_name: volttron1
    hostname: volttron1
    image: volttron/volttron:develop
    ports:
      # host_port:container_port
      # http port for volttron central
      - 8080:8080
    volumes:
      - ./platform_config.yml:/platform_config.yml
      - ./configs:/home/volttron/configs
    environment:
      - CONFIG=/home/volttron/configs
      - LOCAL_USER_ID=1000
